name: Deploy MultiDocker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t votasbanned/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true votasbanned/react-test npm test -- --coverage

      - run: docker build -t votasbanned/multi-client-10-14 ./client
      - run: docker build -t votasbanned/multi-nginx-10-14 ./nginx
      - run: docker build -t votasbanned/multi-server-10-14 ./server
      - run: docker build -t votasbanned/multi-worker-10-14 ./worker

      - run: docker push votasbanned/multi-client-10-14
      - run: docker push votasbanned/multi-nginx-10-14
      - run: docker push votasbanned/multi-server-10-14
      - run: docker push votasbanned/multi-worker-10-14